CREATE TABLE IF NOT EXISTS familias_inscricoes (
  id_inscricao INT AUTO_INCREMENT PRIMARY KEY,
  protocolo CHAR(12) NULL UNIQUE,
  responsavel_cpf CHAR(11) NOT NULL,
  crianca_nome VARCHAR(150) NOT NULL,
  crianca_cpf CHAR(11) NULL,
  crianca_nascimento DATE NOT NULL,
  crianca_sexo ENUM('F','M','NAO_INFORMADO') NOT NULL DEFAULT 'NAO_INFORMADO',
  crianca_pcd BOOLEAN NOT NULL DEFAULT FALSE,
  crianca_pcd_tipos TEXT NULL,
  crianca_etapa ENUM('bercario1','bercario2','maternal1','maternal2','pre','futuro') NOT NULL,
  data_corte DATE NOT NULL,
  renda_valor DECIMAL(10,2) NULL,
  pessoas_domicilio SMALLINT NULL,
  pontuacao_total SMALLINT NOT NULL DEFAULT 0,
  indice_alcance_contato TINYINT NOT NULL DEFAULT 0,
  fase ENUM('recebida','validacao','classificada','convocada','matriculada') NOT NULL DEFAULT 'recebida',
  desfecho ENUM('','em_fila','convocado','confirmado','matriculado','recusado','desistiu') NOT NULL DEFAULT '',
  lgpd_aceite BOOLEAN NOT NULL DEFAULT FALSE,
  prazo_aceite BOOLEAN NOT NULL DEFAULT FALSE,
  assistido BOOLEAN NOT NULL DEFAULT FALSE,
  fora_recomendacao BOOLEAN NOT NULL DEFAULT FALSE,
  fora_motivo VARCHAR(255) NULL,
  id_convocacao INT NULL,
  enviado_em DATETIME NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_responsavel_cpf (responsavel_cpf),
  FOREIGN KEY (id_convocacao) REFERENCES convocacoes(id_convocacao)
);
